config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'pages#home'
  
  resources :conversations, only: [:index, :create] do
  	resources :messages, only: [:index, :create]
  end

  resources :documents

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

		scope :involving, -> (user) do
			where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
		end
    
		scope :between, -> (sender_id, recipient_id) do
			where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
		end
  
end

app/models/document.rb
class Document < ApplicationRecord
  
	has_attached_file :doc
    validates_attachment_content_type :doc, content_type: /\Aimage/ 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime("%v")
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :all_except, -> (user) { 
  	where.not(id: user) 
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

	before_action :authenticate_user!

	def index
		@users = User.all
		@conversations = Conversation.involving(current_user)
	end

	def create
		if Conversation.between(params[:sender_id], params[:recipient_id]).present?
			@conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
		else
			@conversation = Conversation.create(conversation_params)
		end

		redirect_to conversation_messages_path(@conversation)
	end


	private
		def conversation_params
			params.permit(:sender_id, :recipient_id)
		end


	 
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

	def index
		@documents = Document.order('created_at')
	end

	def new
		@document = Document.new
	end

	def create
	  @document = Document.new(doc_params)
		if @document.save
			params[:document][:doc].each do |d| #iterate over multiple attached files     
            @document.create(doc: d)
            end
			flash[:success] = "The document was added!"
			redirect_to root_path
		else
			render '_new'
		end
	end

	def destroy
    @document = Document.find(params[:id])
    if @document.destroy
      flash[:notice] = "Successfully deleted photo!"
      redirect_to root_path
    else
      flash[:alert] = "Error deleting photo!"
    end
  end

	private

	def doc_params
		params.require(:document).permit(:id, document: {doc: []})
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_conversation

	def index
		if current_user == @conversation.sender || current_user == @conversation.recipient
			@other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
			@messages = @conversation.messages.order("created_at DESC")
		else
			redirect_to conversations_path, alert: "You don't have permission to view this."
		end
	end

	def create
		@message = @conversation.messages.new(message_params)
		@messages = @conversation.messages.order("created_at DESC")

		if @message.save
			respond_to do |format|
				format.js
			end
		end
		
	end

	private

		def set_conversation
			@conversation = Conversation.find(params[:conversation_id])
		end
		def message_params
			params.require(:message).permit(:content, :user_id)
			
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
  def home
  	@documents = Document.order('created_at')

  	@document = Document.new

  	if user_signed_in?
  	  
      @users = User.find_by(params[:id])
      @conversations = Conversation.involving(current_user)
	   
    end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_index.html.erb
<div class="container" id="services">
		<div class="col-lg-8 col-md-offset-2" id="progpos"><h1>Instant Messenger</h1>
			<% if @users %>
			  <% if current_user.is_admin? %>
			    <% @users_in = User.all_except(current_user) %>
			  	<% @users_in.each do |user| %>
			  	<%= user.email %>
				  <%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @users.id), method: 'post', class: "btn btn-primary" %><br><br/>
				  <% end %>
			  <% else %>

					<%= link_to "Talk to Neo", conversations_path(sender_id: current_user.id, recipient_id: @users = 2 ), method: 'post', class: "btn btn-primary" %>

				<% end %>
				<br>
			<% end %>
			
			<% if !user_signed_in? %>

			  <div><p>Please <%= link_to " sign in", new_user_session_path %> or <%= link_to " register", new_user_registration_path %> to talk to Neo now!</p></div>

			<% end %>
	  </div>	
	  </div>

    <% if !@conversations.nil? %>
			<div class="panel panel-default" id="convo">
				<div class="panel-heading"><h3 id="services">Your conversations</h3></div>
					<div class="panel-body">
						<div class="container">
						  
								<% @conversations.each do |conversation| %>
									<% other = conversation.sender == current_user ? conversation.recipient : conversation.sender %>

									<%= link_to conversation_messages_path(conversation) do %>
										<% if conversation.messages.count > 0 %>
											<div class="col-md-2">
												<%= other.email %><br>
												<%= conversation.messages.last.message_time %>
											</div>
											<div class="col-md-8">
												<%= conversation.messages.last.content %>
											</div>
										<% end %>
									</div>
								<% end %>
							<% end %>	
					</div>
				</div>
			</div>
		<% end %>
    

app/views/documents/_documents.html.erb
<div class="container">
	<div class="row around-xs">
	    <center>
		<% @documents.each do |document| %>
	    
	      <li class="col-xs-3" id="item-grid">
	        <%= link_to image_tag(document.doc.url, class: 'media-object', size:"108x152"), document.doc.url, target: '_blank' %>
	        <% if @users %>
		        <% if current_user.is_admin? %>
							<%= link_to 'Remove', document_path(document), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
						<% end %>
					<% end %> 
				</li>
	    
		<% end %>  
		</center>
	</div>
</div>

app/views/documents/_form.html.erb
<%= form_for @document, multipart: true do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/_index.html.erb
<div class="container">
	<div class="row around-xs">
	    <center>
		<% @documents.each do |document| %>
	    
	      <li class="col-xs-3" id="item-grid">
	        <%= link_to image_tag(document.doc.url, class: 'media-object', size:"108x152"), document.doc.url, target: '_blank' %>
	        <% if @users %>
		        <% if current_user.is_admin? %>
							<%= link_to 'Remove', document_path(document), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
						<% end %>
					<% end %> 
				</li>
	    
		<% end %>  
		</center>
	</div>
</div>

  

app/views/documents/_new.html.erb
<% if @users %>
  <% if current_user.is_admin? %>

    <%= form_for @document do |f| %>
      <% if @document.errors.any? %>
        <div id="error_explanation">
        
          <h2>
            <%= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:" %>
          </h2>

          <ul>
            <% @document.errors.full_messages.each do |msg| %>

              <li>
                <%= msg %>
              </li>
            <% end %>

          </ul>
        </div>
      <% end %>
      
      <div class="form-group" style="width: 20%">
        <%= f.file_field :doc, class: 'form-control', placeholder: "Document", multiple: true %>
      </div>

      <div class="form-group">
        <%= f.submit 'Upload Document', class: 'btn btn-default' %>
      </div>

    <% end %>
  <% end %>
<% end %>

app/views/documents/index.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<div class="media">
  <% @documents.each do |document| %>
    <div class="media-left">
      <!-- Renders image -->
      <%= link_to 'documents', @document.doc.url %>
    </div>
    <div class="media-body">
     <h4>this</h4>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProMo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  	<%= render 'shared/navbar' %>

    <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="panel">
	<div class="panel-body">
		<strong><%= message.user.email %></strong>
		<span class="pull-right"><%= message.message_time %></span>
		<br>
		<div class="row-space-2">
			<%= message.content %>
		</div>
	</div>
</div>

app/views/messages/create.js.erb
<% publish_to conversation_messages_path(@conversation) do %>
$('#chat').prepend("<%= j render @message %>");
<% end %>
$('#new_message')[0].reset();

app/views/messages/index.html.erb
<div class="row">

		<div class="col-md-3 text-center" id="heading">
			<h4><%= @other.email %></h4>
		</div>

	<div class="col-md-9">
		
		<div class="panel panel-default">
			
			<div class="panel-heading">
				Conversation with <%= @other.email %>
			</div>

			<div class="panel-body">
				<div class="container">
						
						<%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
							
							<div class="form-group" id="textbox">
								<%= f.text_field :content, placeholder: "Press enter to send", class: "form-control" %>
							</div>
							
							<%= f.hidden_field :user_id, value: current_user.id %>

							<div class="actions">
								<%= f.submit "Send Message", class: "btn btn-primary" %>
							</div>
						
						<% end %>

						
						
				
				</div>

			</div>
		</div>
		
		<% render @messages, locals: {conversation: @conversation} %> 
	
	</div>

</div>
<% subscribe_to conversation_messages_path(@conversation) %>

app/views/pages/home.html.erb
 <!-- Intro Section -->
<br>
<br>
<br>
  <section id="intro" class="intro-section">
      <div class="container">
        
          <div class="row1" id="text">
              <div class="col-lg-12">
                  <div class="img-circle"><%= image_tag('neosleeping.jpg', class: "img-circle") %></div><h1 class="introheader">Copywriter Profile</h1>
                  <p>Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! </p>
                  <p>Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! Hi, I'm Neo, love me! </p>
              </div>
          </div>
      </div>
  </section>

  <br>
  <br>
  <br>
  <br>
 
  <section id="services" class="services-section">
      <div class="container">
         <div class="col-lg-8 col-md-offset-2" id="progpos">
            <h1>My Skills</h1>
              <br>
              <p id="label">Refined Writing Skills</p>
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style="width:70%">
                  <span class="sr-only">70% Complete</span>
                </div>
              </div>
              <br>
              <p id="label">Sense of Adventure and Curiosity</p>
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style="width:90%">
                  <span class="sr-only">70% Complete</span>
                </div>
              </div>
              <br>
              <p id="label">Research Skills</p>
              <div class="progress ">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style="width:75%">
                  <span class="sr-only">70% Complete</span>
                </div>
              </div>
              <br>
              <p id="label">The Ability to Create Something new</p>
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style="width:85%">
                  <span class="sr-only">70% Complete</span>
                </div>
              </div>
              <br>
              <p id="label">An Understanding of User Experience</p>
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style="width:80%">
                  <span class="sr-only">70% Complete</span>
                </div>
              </div>
              <br>
              <p id="label">Writing with Empathy</p>
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style="width:70%">
                  <span class="sr-only">70% Complete</span>
                </div>
              </div>  
              
          </div>
      </div>
  </section>

  <br> 
  <br>
  <br>
  <br>

  <section id="about" class="about-section">
    <div class="container" id="services">
      <div class="col-lg-8 col-md-offset-2" id="progpos"><h1>My Work</h1></div>

        <%= render 'documents/documents' %>
        <br>
        <%= render 'documents/new' %>

      </div>
  </section>

  <br>
  <br>
  <br>
  <br>
  <!-- Contact Section -->
  <section id="contact" class="contact-section">
    <div class="container">
                  
    <%= render 'conversations/index' %>
                
    </div>
  </section>
 

  <br>
  <br>
  <br>
  <br>

app/views/shared/_navbar.html.erb
<div><%= image_tag('vintage2.jpg', class: "img-responsive", style: 'display: block; margin: 0; width: 100%; margin-top: -62px;') %></div>
      

<body id="page-top" data-spy="scroll" data-target=".navbar-static-top">

  <nav class="navbar navbar-default navbar-static-top" role="navigation" id="topnavbar">
      <div class="container">
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand navbar-brand" href="/" id="nav-link">Neo Lee - Copywriter</a>
          </div>

          <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav">
                <% if current_page?('/') %>
                <li>
                    <a class="page-scroll" href="#services" id="nav-link">Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#about" id="nav-link">My Work</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact" id="nav-link">Instant Messenger</a>
                </li>
                <% end %>

                <% if(!user_signed_in?) %>
                  
                  <li><%= link_to "Log In", new_user_session_path, id: "nav-link" %></li>
                  <li><%= link_to "Register to chat", new_user_registration_path, id: "nav-link" %></li>
                  
                <% else %>
                  
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, id: "nav-link" %></li>
                
                <% end %>
                
              </ul>
          </div>     
      </div>
  </nav>